### ISSUE TITLE
Pousser au lieu de tirer…

### ISSUE THREAD

**Issue by PhilipFou** [benallemand/ufolep13volley#78]
Envoi automatique des éléments d'un match (feuille de match et fiches équipes) au responsable en charge du contrôle de la division concernée par ce match (et à condition que celui-ci ait donné son accord).
Pour moi, l'accord est donné !

Philip (je ne sais pas trop encore comment je vais apparaître dans ta liste de choses à faire, donc je signe)

**Comment by benallemand** [comment]
c'est fait !
