### ISSUE TITLE
Incrémentation report d'une équipe

### ISSUE THREAD

**Issue by PhilipFou** [benallemand/ufolep13volley#82]
Et si… d'un petit test 
Team A asks for a report
Team B accepts the report
Then Team A is 1 report
On libérait l'obligation du responsable de division d'incrémenter manuellement ? Je crois  que nous en avons déjà parlé. Le seul cas de figure où l'automatisme n'est pas bon c'est en cas de "force majeure" (la neige vendredi soir) mais là en général la demande ne se fait pas par le site et même si elle se fait par ce biais, que c'est accepté, le responsable de division peut désincrémenter, ce qui au final arrivera moins souvent que les demandes de report à incrémenter à la main.
Qu'en penses-tu ?

**Comment by benallemand** [comment]
hello,
ok, par contre on est d'accord que le titre du ticket est erroné et qu'il faut lire "report" au lieu de "forfait" ?

**Comment by benallemand** [comment]
donc je prévois le report compté automatiquement, et la décrémentation pourra être faite par le responsable à l'appréciation de la raison énoncée.

**Comment by benallemand** [comment]
hello, j'ai fait la modif !
