### ISSUE TITLE
Refus de report

### ISSUE THREAD

**Issue by PhilipFou** [benallemand/ufolep13volley#85]
Lorsque l'on clique pour refuser une demande de report, un message automatique est envoyé. Fort bien. Serait-il possible de prévoir d'ajouter, si nécessaire, une explication ? Soit par un champ libre (le plus simple) soit par des cas prévus, comme par exemple "Maximum de report pour l'équipe Y déjà atteint".

**Comment by benallemand** [comment]
C'est fait !
